
-- When creating new DB, you've to enable POSTGIS extension. Typing these commands in the query window.

CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;

-- creating object id table with unique ID's
-- Unique IDs are generated by using python uuid library
-- there limit is calculated by scanning total number of rows in the trajectory.csv file
create table obj (
	obj_id integer primary key,
	unique_id text
)

-- creating POI table with unique id retrieved from .json files
-- This unique id is provided by google places api
		   
 create table poi(
 	poi_id text primary key,
 	geom_point geometry -- I'm adding POINT inside the datasets using python script. Just mentioning it as "geometry(POINT, 4326)" doesn't work.
)

-- This statement assigns the srid to geometry column
update poi set geom_point = st_setsrid(geom_point, 4326)  

-- Creating table for trajectory data.

 create table traj (
 	traj_id integer primary key, 
	obj_id integer references obj(obj_id),
 	total_distance text, 
 	travel_time text, 
	traj_path geometry -- Adding LINESTRING in the data column through notepad++
 )
 
-- Assigning SRID to traj_path column.
update traj set traj_path = st_setsrid(traj_path, 4326) 

-- storing grid ids related to different generated grids. 

create table grids (
	grid_id float primary key,
	x_dim integer,
	y_dim integer
)
			
-- From the python code we divide the area into specified grids. Grids are dynamic and can be specified in x & y dimensions i.e. 4x4, 5x6 & 10x7 etc.
-- Storing grid cells

create table cells (
	cell_id integer primary key,
	grid_id float references grids(grid_id),
	cell_names text,
	coordinates geometry -- Creating POLYGON geometry: need to specify first and last coordinate same for each of them. 
)

-- Assigning SRID to coordinates column.
update cells set coordinates = st_setsrid(coordinates, 4326) 

		
			
			
















			